import os
import re

chapters_dir = 'chapters'
citation_pattern = re.compile(r'\\cite[p]?\{([^}]+)\}')

def clean_citations(text):
    def replacer(match):
        command = match.group(0).split('{')[0] # \cite or \citep
        keys = match.group(1).split(',')
        valid_keys = []
        for key in keys:
            key = key.strip()
            # If the key starts with '10_' it is an autogenerated DOI key.
            if not key.startswith('10_'):
                valid_keys.append(key)
        
        if not valid_keys:
            return '' # Remove the citation entirely if no valid keys left
        else:
            return f"{command}{{{', '.join(valid_keys)}}}"
            
    # Keep replacing until no more changes (in case of nested or multiple on same line)
    new_text = citation_pattern.sub(replacer, text)
    # clean up any leftover spaces if citation was removed
    new_text = re.sub(r'\s+~?\s*(?=[.,;])', '', new_text) # remove space before punctuation
    new_text = re.sub(r' \s+', ' ', new_text) # remove double spaces
    return new_text

for filename in os.listdir(chapters_dir):
    if filename.endswith('.tex'):
        filepath = os.path.join(chapters_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        cleaned_content = clean_citations(content)
        
        if cleaned_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(cleaned_content)
            print(f"Cleaned {filename}")
